"""
Structured models for trading plans and actions.
"""

from enum import Enum
from typing import List

from pydantic import BaseModel, Field


class TradeDirection(str, Enum):
    """Direction of the trade."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class TradeAction(BaseModel):
    """
    A single trade action to be executed on a specific chain.
    """

    chain: str = Field(
        ...,
        description="The blockchain to execute on (solana, sepolia, avalanche-fuji)",
    )
    asset: str = Field(..., description="The asset symbol (e.g., ETH, SOL, AVAX)")
    amount: float = Field(
        ...,
        description="Amount of USDC to spend (BUY) or asset to sell (SELL)",
    )
    direction: TradeDirection = Field(..., description="Buy or Sell")


class TradePlan(BaseModel):
    """
    A collection of trade actions generated by the Planner.
    """

    actions: List[TradeAction] = Field(
        default_factory=list, description="List of actions to take"
    )
    rationale: str = Field(..., description="The reasoning behind this plan")
    risk_level: str = Field(..., description="Low, Medium, or High risk assessment")
